[workspace]
members = [
    "probe-rs",
    "probe-rs-target",
    "probe-rs-cli-util",
    "cli",
    "gdb-server",
    "smoke-tester",
]

[profile.release]
debug = true

[patch."https://github.com/jonas-schievink/jaylink"]
jaylink = { path = "../jaylink" }